- name: This playbook will install nginx, configures nginx to serve web pages from custom folder and deploys a custom web page
  hosts: all
  tasks:
  - name: Install nginx in Ubuntu
    apt: name=nginx state=latest update_cache=yes
