- name: This playbook will install nginx, configures nginx to serve web pages from custom folder and deploys a custom web page
  hosts: all
  tasks:
  - name: Install nginx in Ubuntu
    apt: name=nginx state=latest update_cache=yes

  - name: Start the nginx server in Ubuntu
    service: name=nginx state=started 

  - name: Create the custom web root folder
    file: path=/var/html state=directory mode=0777

  - name: Configure nginx server to serve html pages from our custom folder in Ubuntu
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx service to apply the config changes
    service: name=nginx state=restarted

  - name: Deploy custom html page
    copy: src=index.html dest=/var/html/index.html
