- name: First Play
  hosts: ubuntu1
  tasks:
  - name: Ping ansible node
    ping:

  - debug: msg="First Play, second Task"

- name: Second Play
  hosts: ubuntu2
  tasks:
  - name: Ping ansible node
    ping:

  - debug: msg="Second Play, second Task"
