- name: Check if nginx server is already running in Rocky
  shell: curl http://localhost
  register: output
  ignore_errors: yes

- debug: var=output

- name: Start the nginx server in Rocky 
  when: output.rc != 0
  shell: nginx
